# Generated by Django 3.1.7 on 2021-08-01 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('day', models.DateTimeField(default=datetime.datetime(2021, 8, 2, 0, 33, 58, 617317))),
                ('reminder', models.BooleanField(default=False)),
            ],
        ),
    ]
